### ISSUE TITLE
web page missing image

### ISSUE THREAD

**Issue by Cyrille37** [ncarlier/nunux-keeper#4]
This page is not well "keeped":
http://www.pressesdesmines.com/traces-numeriques-et-territoires.html
Missing image

Cheers

**Comment by ncarlier** [comment]
It's because the image is out of the main content of the document. The image is mix with buttons and forms. So the content extraction algorithm ignore the image. You can bypass this behavior by using the bookmarklet. Call the bookmarklet on the page. Select, with the mouse, what you want to keep and drag and drop the selection onto the bookmarklet. And click save. The image will be saved.... but also the form. However, you could edit the document to remove unwanted elements.

**Comment by Cyrille37** [comment]
Wouah! What's a great feature. Thanks
