### ISSUE TITLE
document in several categories

### ISSUE THREAD

**Issue by Cyrille37** [ncarlier/nunux-keeper#7]
It should be nice to get a document in several categories. Or at least in "one category" and the "public" one. Or "public" could be a "tag" nore a "category".

Cheers

**Comment by ncarlier** [comment]
Hello,

It is already the case but the feature is a bit hidden and not well documented. You can drag and drop a document card on a category (on the left panel) to add this category to the document.
I still have to make this feature more visual and mobile compliant (because drag and drop is not possible on mobile view)

thx

**Comment by Cyrille37** [comment]
It does not work.
I'd try but that moves the doc from the previous category. I'd try with Shift and/or Ctrl but it does not change.

**Comment by ncarlier** [comment]
Yikes! You are right. It's a bug.

Thx

**Comment by ncarlier** [comment]
Fixed

**Comment by Cyrille37** [comment]
Phew, we are saved!
;-)
